slam_toolbox:
  use_sim_time: true
  map_file_name: /tmp/map
  resolution: 0.05
  max_laser_range: 10.0
  minimum_time_interval: 0.5
  transform_publish_period: 0.05
  map_update_interval: 5.0
  mode: "mapping"
